[package]
edition = "2021"
name = "tchread"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
binrw = "0.11.1"
num-traits = "0.2.15"
structopt = "0.3.26"

[[bin]]
name = "rs-tchread"
path = "src/main.rs"
